name: C_C++_CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - reuseable-workflow


jobs:
  build:
    uses: NWChemEx-Project/.github/.github/workflows/c-cpp_tmpl.yml@reuseable-workflow
    with: 
      dependencies: 'gcc gcovr cmake openblas cblas lapacke scalapack boost eigen3 openmpi cppyy numpy'
    secrets:
      CPP_GITHUB_TOKEN: ${{ secrets.CPP_GITHUB_TOKEN }}