name: Build and Deploy Documentation
on:
  push:
    branches:
      - master

jobs:
  Build-Documentation:
    uses: NWChemEx-Project/.github/.github/workflows/deploy_docs_tmpl.yaml@master
    with: 
      target: nwchemex_cxx_api
      dependencies: cmake doxygen sphinx gcc ninja gcovr openblas cblas lapacke scalapack boost eigen3 openmpi cppyy numpy libint
      generate_modules_docs: true
    secrets:
      CMAIZE_GITHUB_TOKEN: ${{ secrets.CMAIZE_GITHUB_TOKEN }}
